default:
  image: node:16.14.0-alpine

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "의존성 설치 시작"
    - npm install
    - echo "Test 시작"
    - npm run test

deploy:
  stage: deploy
  only:
    - develop
  before_script:
    # ssh 연결하기 위해 세팅
    - which ssh-agent || ( apk add --no-cache openssh-client rsync)
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
    - chmod 644 ~/.ssh/id_rsa.pub
    - echo "$SSH_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - echo "배포를 시작하겠습니다."
    - echo "PORT=$PORT" >> .env && echo "DB_ID=$DB_ID" >> .env && echo "DB_PW=$DB_PW" >> .env && echo "SECRET=$SECRET" >> .env
    - rsync -avz --exclude='node_modules' -e "ssh -i ~/.ssh/id_rsa" ./ $SERVER_USER@$SERVER_IP:/home/elice/app
    - ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/elice/.nvm/versions/node/v16.14.0/bin'; cd /home/elice/app; npm install && npm run deploy && exit"
    - echo "서버에 배포가 끝났습니다."
